server:
  port: 8087
spring:
  application:
    name: spring-cloud-alibaba-config
  cloud:
    nacos:
      config: #discovery:
        server-addr: http://39.108.236.35:8848
        file-extension: yml
        #        prefix: febs
        #        namespace: '2ef2186e-078c-4904-8643-ff5e90555456'
        #        group: GROUP_A
        #        extension-configs:
        #          - dataId: ext-config-one.yaml
        #            group: DEFAULT_GROUP
        #            refresh: true
        #          - dataId: ext-config-one.yaml
        #            group: DEFAULT_GROUP
      #            refresh: false
      # shared-configs: ext-config-one.yaml,ext-config-two.yaml
#动态刷新配置 ---需要忽略权限拦截
#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh